# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/luis/FIRMWARE/git/vhdl/ip_blocks/axi_to_stellarip/vivado_prj/vivado_prj.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luis/FIRMWARE/git/vhdl/ip_blocks/axi_to_stellarip/vivado_prj/vivado_prj.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/luis/FIRMWARE/git/vhdl/ip_blocks/axi_to_stellarip/vivado_prj/vivado_prj.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0.xci
# IP: The module: 'axi_traffic_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/luis/FIRMWARE/git/vhdl/ip_blocks/axi_to_stellarip/vivado_prj/vivado_prj.srcs/sources_1/ip/axi_traffic_gen_0/axi_traffic_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_traffic_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
